modLoader="javafml"
loaderVersion="[2,)"
license="GNU GPL v3"

[[mixins]]
config="rocketnautics.mixins.json"
[[mixins]]
config="dimensional_sable.mixins.json"

[[mods]]
modId="rocketnautics"
version="${file.jarVersion}"
displayName="Create: Cosmonautics"
displayURL="https://github.com/CosmonauticsTeam/Create-Cosmonautics"
authors="webyep-art, M_W_K"
description='''
Space addon for Create Aeronautics!
'''

[[mods]]
modId="dimensional_sable"
version="1.0.5"
displayName="Dimensional Sable"
description='''Dimensional Support for Sable'''

[[dependencies.rocketnautics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.rocketnautics]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rocketnautics]]
    modId="create"
    mandatory=true
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rocketnautics]]
    modId="aeronautics"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rocketnautics]]
    modId="dimensional_sable"
    mandatory=true
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dimensional_sable]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dimensional_sable]]
    modId="sable"
    mandatory=true
    versionRange="[2.0.3,)"
    ordering="NONE"
    side="BOTH"
