package dev.devce.rocketnautics.content.blocks;

import com.simibubi.create.foundation.blockEntity.SmartBlockEntity;
import com.simibubi.create.foundation.blockEntity.behaviour.BlockEntityBehaviour;
import com.simibubi.create.foundation.blockEntity.behaviour.CenteredSideValueBoxTransform;
import com.simibubi.create.foundation.blockEntity.behaviour.scrollValue.ScrollValueBehaviour;
import dev.devce.rocketnautics.RocketConfig;
import dev.devce.rocketnautics.registry.RocketTags;
import dev.ryanhcode.sable.api.block.BlockEntitySubLevelActor;
import dev.ryanhcode.sable.api.physics.handle.RigidBodyHandle;
import dev.ryanhcode.sable.sublevel.ServerSubLevel;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.Vec3;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.capability.IFluidHandler;
import net.neoforged.neoforge.fluids.capability.templates.FluidTank;
import org.joml.Vector3d;

import java.util.List;

public class RocketThrusterBlockEntity extends AbstractThrusterBlockEntity {
    private static int getMaxFuelConsumption() {
        return RocketConfig.SERVER.maxFuelConsumption.get();
    }

    private static int getSteamMinFlow() {
        return RocketConfig.SERVER.steamMinFlow.get();
    }

    private static int getIgnitionFlow() {
        return RocketConfig.SERVER.ignitionFlow.get();
    }

    private static final float MIN_THROTTLE_CHANGE = 0.01f;

    public FluidTank fuelTank = new FluidTank(1000, fluid -> true);
    public ScrollValueBehaviour minThrust;
    public ScrollValueBehaviour maxThrust;
    public ThrustBehaviour thrust;

    @Override
    public ScrollValueBehaviour getThrustPower() {
        return maxThrust;
    }

    /** Physics force group for all rocket-related thrust. */
    public static final dev.ryanhcode.sable.api.physics.force.ForceGroup ROCKET_FORCE = new dev.ryanhcode.sable.api.physics.force.ForceGroup(
            Component.literal("Rocket Thrust"),
            Component.literal("Thrust generated by rocket engines"),
            0x3366FF,
            true);

    public boolean currentlyBurning = false;
    public float fuelThrottle = 0.0f;
    private float internalFlow = 0.0f;
    private boolean targetActive = true; // Default to ON
    private int startupTicks = 0;
    public int currentFuelUsage = 0;
    private int totalAvailableFuel = 0;
    private float currentIspMultiplier = 1.0f;
    private float currentEfficiencyMultiplier = 1.0f;
    private int burnoutDelay = 0;
    private boolean steamMode = false;
    private float targetThrottle = 1.0f; // Default to Full Throttle

    // Gimbal state
    public Vector3d gimbalOffset = new Vector3d(0, 0, 0);

    @Override
    public int getWarmupTime() {
        return 40;
    }

    public RocketThrusterBlockEntity(BlockEntityType<?> type, BlockPos pos, BlockState state) {
        super(type, pos, state);
    }

    @Override
    public void addBehaviours(List<BlockEntityBehaviour> behaviours) {
        minThrust = new ScrollValueBehaviour(
                Component.translatable("gui.rocketnautics.min_thrust"),
                this,
                new CenteredSideValueBoxTransform(
                        (state, direction) -> direction != state.getValue(RocketThrusterBlock.FACING)));
        minThrust.between(0, 20);
        minThrust.withFormatter(v -> (v * 50) + " N");
        minThrust.setValue(0);

        maxThrust = new ScrollValueBehaviour(
                Component.translatable("gui.rocketnautics.max_thrust"),
                this,
                new CenteredSideValueBoxTransform(
                        (state, direction) -> direction != state.getValue(RocketThrusterBlock.FACING)));
        int limit = RocketConfig.SERVER.brokenBarrier.get() ? 100 : 20;
        maxThrust.between(0, limit);
        maxThrust.withFormatter(v -> (v * 50) + " N");
        maxThrust.setValue(limit);

        thrust = new ThrustBehaviour(this)
                .withType(ThrustBehaviour.EngineType.ROCKET)
                .withOffset(new Vec3(0.5, 0.5, 0.5));

        behaviours.add(minThrust);
        behaviours.add(maxThrust);
        behaviours.add(thrust);
    }

    /**
     * Calculates the current thrust output in Newtons.
     *
     * @return Thrust value based on throttle and min/max settings.
     */
    public int getCurrentPower() {
        if (!isActive())
            return 0;

        int min = minThrust.getValue();
        int max = maxThrust.getValue();
        if (min > max)
            min = max;

        return (int) ((min + (max - min) * fuelThrottle) * targetThrottle);
    }

    @Override
    public boolean isActive() {
        return currentlyBurning;
    }

    protected void updateActiveState() {
        if (level == null || level.isClientSide)
            return;

        boolean wasBurning = this.currentlyBurning;
        float oldThrottle = this.fuelThrottle;
        int oldUsage = this.currentFuelUsage;
        int oldFuel = this.totalAvailableFuel;

        updateFuelProperties();

        int baseConsumption = (int) (getMaxFuelConsumption() * currentEfficiencyMultiplier);
        int targetConsumption = targetActive ? (int) (baseConsumption * Math.max(0.1f, fuelThrottle * targetThrottle))
                : 0;
        int actuallyDrained = attemptFuelDrain(targetConsumption);

        float targetFlow = actuallyDrained / (float) Math.max(1, targetConsumption);

        if (targetFlow > 0) {
            if (startupTicks < 10) {
                startupTicks++;

                float steamCap = (getIgnitionFlow() - 1.0f) / (float) getMaxFuelConsumption();
                this.internalFlow = net.minecraft.util.Mth.lerp(0.2f, this.internalFlow,
                        Math.min(targetFlow, steamCap));
            } else {
                this.internalFlow = net.minecraft.util.Mth.lerp(0.5f, this.internalFlow, targetFlow);
            }
        } else {
            this.internalFlow = net.minecraft.util.Mth.lerp(0.05f, this.internalFlow, 0.00f);
            if (this.internalFlow < 0.001f) {
                this.internalFlow = 0;
                if (burnoutDelay <= 0)
                    startupTicks = 0;
            }
        }

        this.fuelThrottle = internalFlow;

        float effectiveFlow = internalFlow * getMaxFuelConsumption();

        if (effectiveFlow >= (getIgnitionFlow() - 0.5f)) {
            if (startupTicks >= 10 || wasBurning) {
                this.currentlyBurning = true;
                this.steamMode = false;
                this.burnoutDelay = 10;
                if (startupTicks < 10)
                    startupTicks = 10;
            } else {
                this.currentlyBurning = false;
                this.steamMode = true;
            }
        } else if (effectiveFlow >= getSteamMinFlow() || (targetFlow > 0 && startupTicks < 10)) {
            this.currentlyBurning = false;
            this.steamMode = true;
            this.burnoutDelay = 0;
        } else {
            if (burnoutDelay > 0) {
                burnoutDelay--;
            } else {
                this.currentlyBurning = false;
                this.steamMode = false;
                startupTicks = 0;
            }
        }

        this.currentFuelUsage = actuallyDrained;
        this.totalAvailableFuel = fuelTank.getFluidAmount();

        if (wasBurning != currentlyBurning || Math.abs(oldThrottle - fuelThrottle) > MIN_THROTTLE_CHANGE
                || oldUsage != currentFuelUsage || Math.abs(oldFuel - totalAvailableFuel) > 50) {
            sendData();
            setChanged();
        }
    }

    private void updateFuelProperties() {
        FluidStack stack = fuelTank.getFluid();
        if (stack.isEmpty() || !isRocketFuel(stack)) {
            currentIspMultiplier = 1.0f;
            currentEfficiencyMultiplier = 1.0f;
            return;
        }

        String fluidId = net.minecraft.core.registries.BuiltInRegistries.FLUID.getKey(stack.getFluid()).toString()
                .toLowerCase();

        if (fluidId.contains("kerosene")) {
            currentIspMultiplier = 1.4f;
            currentEfficiencyMultiplier = 0.5f;
        } else if (fluidId.contains("diesel") || fluidId.contains("fuel_oil") || fluidId.contains("lpg")) {
            currentIspMultiplier = 1.2f;
            currentEfficiencyMultiplier = 0.7f;
        } else if (fluidId.contains("gasoline") || fluidId.contains("petrol")) {
            currentIspMultiplier = 1.1f;
            currentEfficiencyMultiplier = 0.8f;
        } else {
            currentIspMultiplier = 1.0f;
            currentEfficiencyMultiplier = 1.0f;
        }
    }

    private boolean isRocketFuel(FluidStack stack) {
        if (stack.isEmpty())
            return false;
        if (stack.getFluid().isSame(net.minecraft.world.level.material.Fluids.LAVA))
            return true;
        if (stack.is(RocketTags.FluidTags.ROCKET_FUEL.tag))
            return true;

        String id = net.minecraft.core.registries.BuiltInRegistries.FLUID.getKey(stack.getFluid()).toString();
        return id.contains("tfmg") && (id.contains("kerosene") || id.contains("diesel") || id.contains("gasoline")
                || id.contains("fuel_oil") || id.contains("lpg"));
    }

    private int attemptFuelDrain(int amount) {
        if (fuelTank.getFluidAmount() > 0 && isRocketFuel(fuelTank.getFluid())) {
            int toDrain = Math.min(fuelTank.getFluidAmount(), amount);
            return fuelTank.drain(toDrain, IFluidHandler.FluidAction.EXECUTE).getAmount();
        }
        return 0;
    }

    public Vector3d getParticleDirection() {
        Direction nozzle = getThrustDirection();
        return new Vector3d(nozzle.getStepX(), nozzle.getStepY(), nozzle.getStepZ());
    }

    /**
     * Main ticking logic for the thruster.
     * Handles particle spawning, camera shake, entity damage, and block melting.
     */
    @Override
    public void tick() {
        super.tick();
        if (level == null) return;

        // Runtime limit update for "Break Barrier" command
        int targetMax = RocketConfig.SERVER.brokenBarrier.get() ? 100 : 20;
        if (maxThrust.getValue() > targetMax || (targetMax == 100 && maxThrust.getValue() <= 20 && level.getGameTime() % 20 == 0)) {
            maxThrust.between(0, targetMax);
        }
        if (!level.isClientSide) {
            updateActiveState();
        }

        Direction facing = getThrustDirection();
        thrust.withOffset(new Vec3(0.5, 0.5, 0.5).add(facing.getStepX() * 0.5, facing.getStepY() * 0.5, facing.getStepZ() * 0.5));
        thrust.update(
                getCurrentPower() * 50.0f,
                fuelThrottle,
                new Vec3(facing.getStepX(), facing.getStepY(), facing.getStepZ()),
                isActive()
        );
    }

    @Override
    public void sable$physicsTick(ServerSubLevel serverSubLevel, RigidBodyHandle handle, double deltaTime) {
        thrust.applyPhysicsForce(handle, deltaTime);
    }

    @Override
    protected void write(CompoundTag tag, HolderLookup.Provider registries, boolean clientPacket) {
        super.write(tag, registries, clientPacket);
        tag.putBoolean("Burning", currentlyBurning);
        tag.putBoolean("TargetActive", targetActive);
        tag.putFloat("FuelThrottle", fuelThrottle);
        tag.putInt("FuelUsage", currentFuelUsage);
        tag.putBoolean("SteamMode", steamMode);
        tag.putInt("StartupTicks", startupTicks);
        tag.putInt("TotalFuel", totalAvailableFuel);
        tag.putFloat("TargetThrottle", targetThrottle);
        tag.putFloat("IspMult", currentIspMultiplier);
        tag.put("FuelTank", fuelTank.writeToNBT(registries, new CompoundTag()));

        CompoundTag gimbalTag = new CompoundTag();
        gimbalTag.putDouble("x", gimbalOffset.x);
        gimbalTag.putDouble("y", gimbalOffset.y);
        gimbalTag.putDouble("z", gimbalOffset.z);
        tag.put("Gimbal", gimbalTag);
    }

    @Override
    protected void read(CompoundTag tag, HolderLookup.Provider registries, boolean clientPacket) {
        super.read(tag, registries, clientPacket);
        currentlyBurning = tag.getBoolean("Burning");
        targetActive = tag.getBoolean("TargetActive");
        fuelThrottle = tag.getFloat("FuelThrottle");
        currentFuelUsage = tag.getInt("FuelUsage");
        steamMode = tag.getBoolean("SteamMode");
        startupTicks = tag.getInt("StartupTicks");
        totalAvailableFuel = tag.getInt("TotalFuel");
        targetThrottle = tag.getFloat("TargetThrottle");
        currentIspMultiplier = tag.getFloat("IspMult");
        if (tag.contains("FuelTank")) {
            fuelTank.readFromNBT(registries, tag.getCompound("FuelTank"));
        }
        if (tag.contains("Gimbal")) {
            CompoundTag gimbalTag = tag.getCompound("Gimbal");
            gimbalOffset.set(gimbalTag.getDouble("x"), gimbalTag.getDouble("y"), gimbalTag.getDouble("z"));
        }
    }

    public Direction getThrustDirection() {
        return getBlockState().getValue(RocketThrusterBlock.FACING);
    }

    @Override
    public boolean addToGoggleTooltip(List<Component> tooltip, boolean isPlayerSneaking) {
        tooltip.add(
                Component.literal("    ").append(Component.translatable(getBlockState().getBlock().getDescriptionId())
                        .withStyle(net.minecraft.ChatFormatting.GOLD)));

        tooltip.add(Component.literal("  ").append(Component.translatable("rocketnautics.goggles.status")).append(": ")
                .append(isActive()
                        ? Component.translatable("rocketnautics.goggles.active")
                                .withStyle(net.minecraft.ChatFormatting.GREEN)
                        : (steamMode
                                ? Component.literal("Steam (Warmup)").withStyle(net.minecraft.ChatFormatting.YELLOW)
                                : Component.translatable("rocketnautics.goggles.inactive")
                                        .withStyle(net.minecraft.ChatFormatting.RED))));

        int power = getCurrentPower();
        tooltip.add(Component.literal("  ").append(Component.translatable("rocketnautics.goggles.thrust")).append(": ")
                .append(Component.literal(power * 50 + " N").withStyle(net.minecraft.ChatFormatting.GOLD)));

        int flowPerSecond = currentFuelUsage * 20;
        tooltip.add(Component.literal("  Flow Rate: ")
                .append(Component.literal(flowPerSecond + " mB/s").withStyle(net.minecraft.ChatFormatting.AQUA)));

        if (totalAvailableFuel > 0) {
            String fuelName = fuelTank.getFluid().getHoverName().getString();
            tooltip.add(
                    Component.literal("  ").append(Component.translatable("rocketnautics.goggles.fuel")).append(": ")
                            .append(Component.literal(fuelName + " (" + totalAvailableFuel + " mB)")
                                    .withStyle(net.minecraft.ChatFormatting.AQUA)));
        }

        if (currentIspMultiplier > 1.01f) {
            tooltip.add(Component.literal("  Fuel Quality: ")
                    .append(Component.literal(String.format("+%.0f%% Efficiency", (currentIspMultiplier - 1.0f) * 100))
                            .withStyle(net.minecraft.ChatFormatting.GREEN)));
        }

        return true;
    }

    public int getStartupTicks() {
        return startupTicks;
    }

    public int getBurnoutDelay() {
        return burnoutDelay;
    }

    public float getCurrentIspMultiplier() {
        return currentIspMultiplier;
    }

    public float getCurrentEfficiencyMultiplier() {
        return currentEfficiencyMultiplier;
    }

    public boolean isSteamMode() {
        return steamMode;
    }

    @Override
    public void setActive(boolean active) {
        this.targetActive = active;
        notifyUpdate();
    }

    @Override
    public void setThrottle(float throttle) {
        this.targetThrottle = Math.max(0.0f, Math.min(1.0f, throttle));
        setChanged();
        sendData();
    }

    @Override
    public void writeValue(String key, double value) {
        if ("throttle".equals(key)) {
            setActive(value > 0);
            setThrottle((float) value);
        } else if ("thrust".equals(key)) {
            setActive(value > 0);
            var behavior = getThrustPower();
            if (behavior != null) {
                float maxN = behavior.getValue() * 50.0f;
                setThrottle(maxN > 0 ? (float)(value / maxN) : 0);
            } else {
                setThrottle((float) value);
            }
        }
    }

    @Override
    public void writeValues(String key, double... values) {
        // Thruster doesn't have multi-value keys yet, but could add gimbal here if
        // needed
    }

    @Override
    public void setGimbal(double pitch, double yaw) {
        // Standard thruster has no gimbal
    }

    @Override
    public float getFlow() {
        return fuelThrottle;
    }

    @Override
    public String getPeripheralType() {
        return "thruster";
    }
}
